description: Stack com intuito de facilitar o início do desenvolvimento de uma aplicação que use java como sua base
name: java-starter
display-name: Java Starter
picture: stack.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility: # Put a list of technologies compatible with the stack
  - java
  - spring
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies 
  - docker 
about: docs/about.md