name: mapstruct
description: Mapeamento descomplicado sem o uso de reflections
display-name: Mapstruct
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
# use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "Api"
  - "Java"
  - "Springboot"
types:
  - app

hooks:
  - type: edit
    trigger: after-render
    path: app/pom.xml
    changes:
      - search:
          string: "<dependencies>"
          insert-after:
            snippet: snippets/dependencies.txt
          when:
            not-exists: "<groupId>org.mapstruct</groupId>"
      
      - search:
          string: "<properties>"
          insert-after:
            snippet: snippets/properties.txt
          when:
            not-exists: "<org.mapstruct.version>"
      
      - search:
          string: "<plugins>"
          insert-after:
            snippet: snippets/plugins.txt
          when:
            not-exists: "<artifactId>mapstruct-processor</artifactId>"
